### PR TITLE
fix $match usage in user deletion

### LINKED ISSUE #69: 500 - internal error after deleting user from group
Steps:
1. Go to Settings > Groups
2. Press the delete button close to the user

Expected: 
User deleted

Actual:
500 internal server error

```
devicehub-api                   | 2025-01-10T11:32:31.701Z ERR/api:controllers:apiutil 1 [*] Failed to remove group users:  MongoServerError: unknown top level operator: $ne. If you have a field name that starts with a '$' symbol, consider using $getField or $setField.
devicehub-api                   |     at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:202:26)
devicehub-api                   |     at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
devicehub-api                   |     at MessageStream.emit (node:events:519:28)
devicehub-api                   |     at MessageStream.emit (node:domain:488:12)
devicehub-api                   |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:124:16)
devicehub-api                   |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
devicehub-api                   |     at writeOrBuffer (node:internal/streams/writable:570:12)
devicehub-api                   |     at _write (node:internal/streams/writable:499:10)
devicehub-api                   |     at Writable.write (node:internal/streams/writable:508:10)
devicehub-api                   |     at Socket.ondata (node:internal/streams/readable:1007:22)
devicehub-api                   |     at Socket.emit (node:events:519:28)
devicehub-api                   |     at Socket.emit (node:domain:488:12)
devicehub-api                   |     at addChunk (node:internal/streams/readable:559:12)
devicehub-api                   |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
devicehub-api                   |     at Readable.push (node:internal/streams/readable:390:5)
devicehub-api                   |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
devicehub-api                   |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
devicehub-api                   | Trace: error occured here
devicehub-api                   |     at Module.internalError (file:///app/lib/util/apiutil.js:95:13)
devicehub-api                   |     at file:///app/lib/units/api/controllers/groups.js:435:21
devicehub-api                   |     at runNextTicks (node:internal/process/task_queues:60:5)
devicehub-api                   |     at process.processImmediate (node:internal/timers:454:9)
devicehub-api                   |     at process.topLevelDomainCallback (node:domain:160:15)
devicehub-api                   |     at process.callbackTrampoline (node:internal/async_hooks:128:24)
devicehub-api                   | 2025-01-10T11:32:31.701Z INF/api:controllers:apiutil 1 [*] Responding with 500 Internal Server Error undefined
devicehub-nginx                 | 10.211.0.1 - - [10/Jan/2025:11:32:31 +0000] "DELETE /api/v1/groups/3c5b4d8ca6744356a1c07e0506809a7e/users/terasulov@gid.ru HTTP/1.1" 500 55 "http://localhost:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 
```

### PR DESCRIPTION
**Pull request by DaniilSmirnov**

### CODE REVIEW

File: lib/db/api.js [hunk 1]
```diff
@@ -1009,13 +1009,22 @@ export const isRemoveGroupUserAllowed = function(email, targetGroup) {
         }
         return db.connect().then(client => {
             return client.collection('groups').aggregate([
```
Comment (irdkwmnsb) [inline lib/db/api.js:1011]: Are you sure we need aggregate instead of findOne?

Comment (DaniilSmirnov) [reply lib/db/api.js:1011]: Yes, because of using setIntersection. I think it s not possible to use set in find

Comment (irdkwmnsb) [reply lib/db/api.js:1011]: It looks like here setIntersection can be replaced with [$in](https://www.mongodb.com/docs/manual/reference/operator/query/in/#mongodb-query-op.-in)

Comment (DaniilSmirnov) [reply lib/db/api.js:1011]: simplified

**Review by irdkwmnsb — APPROVED** [review]
